<a href="https://colab.research.google.com/github/DrashtySoni/DS-ML-DL/blob/main/RNN%2BGRU%2BLSTM.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Recurrent Neural Networks (RNN) with Keras

![alt txt](https://docs.google.com/drawings/d/e/2PACX-1vRpQYtOzO1U_3yQLf1885kMaja6MsXtJ8QnlqxrfpTgZmb4WpewJXphGdmotYXDB1VE6zlW6cBY_WqR/pub?w=600&h=600)

## Introduction

Recurrent neural networks (RNN) are a class of neural networks that is powerful for
modeling sequence data such as time series or natural language.

Schematically, a RNN layer uses a `for` loop to iterate over the timesteps of a
sequence, while maintaining an internal state that encodes information about the
timesteps it has seen so far.

The Keras RNN API is designed with a focus on:

- **Ease of use**: the built-in `keras.layers.RNN`, `keras.layers.LSTM`,
`keras.layers.GRU` layers enable you to quickly build recurrent models without
having to make difficult configuration choices.

- **Ease of customization**: You can also define your own RNN cell layer (the inner
part of the `for` loop) with custom behavior, and use it with the generic
`keras.layers.RNN` layer (the `for` loop itself). This allows you to quickly
prototype different research ideas in a flexible way with minimal code.

## Setup

In [ ]:
import numpy as np
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

There are three built-in RNN layers in Keras:

1. `keras.layers.SimpleRNN`

2. `keras.layers.GRU`
3. `keras.layers.LSTM`


In [ ]:
model = keras.Sequential()
# Add an Embedding layer expecting input vocab of size 1000, and
# output embedding dimension of size 64.
model.add(layers.Embedding(input_dim=1000, output_dim=64))

# Add a LSTM layer with 128 internal units.
model.add(layers.LSTM(128))

# Add a Dense layer with 10 units.
model.add(layers.Dense(10))

model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, None, 64)          64000     
                                                                 
 lstm_3 (LSTM)               (None, 128)               98816     
                                                                 
 dense_4 (Dense)             (None, 10)                1290      
                                                                 
Total params: 164,106
Trainable params: 164,106
Non-trainable params: 0
_________________________________________________________________


Built-in RNNs support a number of useful features:

- Recurrent dropout, via the `dropout` and `recurrent_dropout` arguments
- Ability to process an input sequence in reverse, via the `go_backwards` argument

For more information, see the
[RNN API documentation](https://keras.io/api/layers/recurrent_layers/).

## Outputs and states

By default, the output of a RNN layer contains a single vector per sample. This vector
is the RNN cell output corresponding to the last timestep, containing information
about the entire input sequence. The shape of this output is `(batch_size, units)`
where `units` corresponds to the `units` argument passed to the layer's constructor.

A RNN layer can also return the entire sequence of outputs for each sample (one vector
per timestep per sample), if you set `return_sequences=True`. The shape of this output
is `(batch_size, timesteps, units)`.

In [ ]:
model = keras.Sequential()
model.add(layers.Embedding(input_dim=1000, output_dim=64))

# The output of GRU will be a 3D tensor of shape (batch_size, timesteps, 256)
model.add(layers.GRU(256, return_sequences=True))

# The output of SimpleRNN will be a 2D tensor of shape (batch_size, 128)
model.add(layers.SimpleRNN(128))

model.add(layers.Dense(10))

model.summary()

Model: "sequential_5"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding_1 (Embedding)     (None, None, 64)          64000     
                                                                 
 gru_1 (GRU)                 (None, None, 256)         247296    
                                                                 
 simple_rnn (SimpleRNN)      (None, 128)               49280     
                                                                 
 dense_5 (Dense)             (None, 10)                1290      
                                                                 
Total params: 361,866
Trainable params: 361,866
Non-trainable params: 0
_________________________________________________________________


# GRU Gated Recurrence Unit RNN with Keras

1. What is a Gated Recurrence Unit GRU?
<img src="https://lh6.googleusercontent.com/GgdN7MLjbqFfHUFFo5iHFU5wvIXUU8hahuCczVL4SCoEXb3TcYXj_HRFU98I9Ir5ghae7yUdkDEHGZYOtaWpKiV7ZSzw-FdRwBhSOa-0FEupTubhKsTrxTvk0lVDkSLq074k4dYH">
2. Creating a Simple GRU RNN with Keras
> 1. Importing the Right Modules to Build a GRU in Keras
> 2. Adding Layers to Your Gated Recurrence Unit Model
3. Training and Testing our GRU RNN on the MNIST Dataset
> 1. Load the MNIST dataset
> 2. Compile the Gated Recurrence Unit GRU RNN model
> 3. Train and Fit the Model
> 4. Test your Gated Recurrence Unit RNN Model

In [ ]:
#2.1 Importing the Right Modules to Build a GRU in Keras
import tensorflow as tf
from tensorflow import keras
from tensorflow.keras import layers

In [ ]:
#2.2 Adding Layers to Your GRU RNN Model
model = keras.Sequential()
model.add(layers.GRU(64, input_shape=(28, 28)))
model.add(layers.BatchNormalization())
model.add(layers.Dense(10))
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 gru (GRU)                   (None, 64)                18048     
                                                                 
 batch_normalization (BatchN  (None, 64)               256       
 ormalization)                                                   
                                                                 
 dense (Dense)               (None, 10)                650       
                                                                 
Total params: 18,954
Trainable params: 18,826
Non-trainable params: 128
_________________________________________________________________
None


In [ ]:
# 3 Training and Testing our GRU Model on the MNIST Dataset
#3.1 Get dataset from keras
mnist = keras.datasets.mnist
(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train/255.0, x_test/255.0
x_validate, y_validate = x_test[:-10], y_test[:-10]
x_test, y_test = x_test[-10:], y_test[-10:]

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
# 3.2 Compile the Keras GRU RNN
model.compile(
    loss=keras.losses.SparseCategoricalCrossentropy(from_logits=True),
    optimizer="sgd",
    metrics=["accuracy"],
)

In [ ]:
# 3.3 Train and Fit the GRU RNN Model
model.fit(
    x_train, y_train, validation_data=(x_validate, y_validate), batch_size=64, epochs=10
)

Epoch 1/10
938/938 [==============================] - 25s 23ms/step - loss: 1.3912 - accuracy: 0.5389 - val_loss: 1.0638 - val_accuracy: 0.6380
Epoch 2/10
938/938 [==============================] - 21s 23ms/step - loss: 0.8150 - accuracy: 0.7288 - val_loss: 0.6269 - val_accuracy: 0.7953
Epoch 3/10
938/938 [==============================] - 19s 20ms/step - loss: 0.5507 - accuracy: 0.8221 - val_loss: 0.7545 - val_accuracy: 0.7464
Epoch 4/10
938/938 [==============================] - 19s 20ms/step - loss: 0.4152 - accuracy: 0.8705 - val_loss: 0.4555 - val_accuracy: 0.8435
Epoch 5/10
938/938 [==============================] - 20s 22ms/step - loss: 0.3278 - accuracy: 0.9011 - val_loss: 0.3744 - val_accuracy: 0.8756
Epoch 6/10
938/938 [==============================] - 21s 23ms/step - loss: 0.2568 - accuracy: 0.9230 - val_loss: 0.2206 - val_accuracy: 0.9338
Epoch 7/10
938/938 [==============================] - 19s 21ms/step - loss: 0.2113 - accuracy: 0.9368 - val_loss: 0.2276 - val_accuracy:

In [ ]:
# 3.4 Test the Keras Gated Recurrence Unit Model
for i in range(10):
    result = tf.argmax(model.predict(tf.expand_dims(x_test[i], 0)), axis=1)    
    print(result.numpy(), y_test[i])

1/1 [==============================] - 0s 427ms/step
[7] 7
1/1 [==============================] - 0s 22ms/step
[8] 8
1/1 [==============================] - 0s 21ms/step
[9] 9
1/1 [==============================] - 0s 20ms/step
[0] 0
1/1 [==============================] - 0s 18ms/step
[1] 1
1/1 [==============================] - 0s 25ms/step
[2] 2
1/1 [==============================] - 0s 19ms/step
[3] 3
1/1 [==============================] - 0s 17ms/step
[4] 4
1/1 [==============================] - 0s 20ms/step
[5] 5
1/1 [==============================] - 0s 19ms/step
[6] 6


Observation - After 10 epochs, the model does quite well at roughly 95% accuracy for both the training and validation data. It predicts all 10 test data points correctly.

# LSTM (Long Short Term Memory)
<img src="https://miro.medium.com/max/1156/1*laH0_xXEkFE0lKJu54gkFQ.png"><br>
The term "long short-term memory" comes from the following intuition.
Simple recurrent neural networks 
have *long-term memory* in the form of weights.
The weights change slowly during training, 
encoding general knowledge about the data.
They also have *short-term memory*
in the form of ephemeral activations,
which pass from each node to successive nodes.
The LSTM model introduces an intermediate type of storage via the memory cell.
A memory cell is a composite unit, 
built from simpler nodes 
in a specific connectivity pattern,
with the novel inclusion of multiplicative nodes.

## **Vanilla LSTM**

In [ ]:
from numpy import array
from keras.models import Sequential
from keras.layers import LSTM
from keras.layers import Dense
from tensorflow.keras import losses

In [ ]:
# univariate data preparation
from numpy import array
 
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	X, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		y.append(seq_y)
	return array(X), array(y)
 
# define input sequence
raw_seq = [10, 20, 30, 40, 50, 60, 70, 80, 90]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# summarize the data
for i in range(len(X)):
	print(X[i], y[i])

[10 20 30] 40
[20 30 40] 50
[30 40 50] 60
[40 50 60] 70
[50 60 70] 80
[60 70 80] 90


The model with even series performs well with sgd as optimizer and Huber loss. Some part of the code is borrowed rest of the modeling is tried by own adjusting the comination of losses and optimizers

In [ ]:
# define input sequence
raw_seq = [2,4,6,8,10]
# choose a number of time steps
n_steps = 3
# split into samples
X, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
X = X.reshape((X.shape[0], X.shape[1], n_features))
# define model
model = Sequential()
model.add(LSTM(50, activation='relu', input_shape=(n_steps, n_features)))
model.add(Dense(1))
model.compile(optimizer='sgd', loss=tf.keras.losses.Huber())
# fit model
model.fit(X, y, epochs=200, verbose=0)
# demonstrate prediction
x_input = array([8, 10, 12])
x_input = x_input.reshape((1, n_steps, n_features))
yhat = model.predict(x_input, verbose=0)
print(yhat)

[[13.382292]]
